apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-login-clave-unica.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-login-clave-unica.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-login-clave-unica.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-login-clave-unica.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
          env:
            - name: NODE_ENV
              value: {{ .Values.enviroment  }}
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
            - name: HOSTNAME
              value: localhost
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-login-clave-unica.secrets" . }}
                  key: jwt-key
            - name: JWT_SECRET_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-login-clave-unica.secrets" . }}
                  key: jwt-refresh-key
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-login-clave-unica.secrets" . }}
                  key: mongo
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-login-clave-unica.secrets" . }}
                  key: cu-client-key
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-login-clave-unica.secrets" . }}
                  key: cu-secret-key
            - name: REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-login-clave-unica.secrets" . }}
                  key: cu-redirect-uri
            - name: JWT_SECRET_CLAVE_UNICA
              valueFrom:
                secretKeyRef:
                  name: {{ include "api-login-clave-unica.secrets" . }}
                  key: cu-jwt-key
            

          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
