{{- $jwtKey := .Values.secrets.jwtKey | default (randAlphaNum 32) | b64enc  }}
{{- $jwtRefreshKey := .Values.secrets.jwtRefreshKey | default (randAlphaNum 32) | b64enc  }}
{{- $mongo :=  .Values.secrets.mongoUrl | b64enc -}}
{{- $cuClientKey := .Values.secrets.cuClientKey | default (randAlphaNum 32) | b64enc  }}
{{- $cuSecretKey := .Values.secrets.cuSecretKey | default (randAlphaNum 32) | b64enc  }}
{{- $cuRedirectUri := .Values.secrets.cuRedirectUri | b64enc -}}
{{- $cuJwtKey := .Values.secrets.cuJwtKey | default (randAlphaNum 32) | b64enc  }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "api-hra-secrets") }}
{{- if $secret }}
{{- $jwtKey = index $secret.data "jwt-key" }}
{{- $jwtRefreshKey = index $secret.data "jwt-refresh-key" }}
{{- $mongo = index $secret.data "mongo"}}
{{- $cuClientKey = index $secret.data "cu-client-key" }}
{{- $cuSecretKey = index $secret.data "cu-secret-key" }}
{{- $cuRedirectUri = index $secret.data "cu-redirect-uri" }}
{{- $cuJwtKey = index $secret.data "cu-jwt-key" }}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (include "api-login-clave-unica.fullname" .) | printf "%s-secrets" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-login-clave-unica.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-key: {{ $jwtKey }}
  jwt-refresh-key: {{ $jwtRefreshKey }}
  mongo: {{ $mongo }}
  cu-client-key: {{ $cuClientKey }}
  cu-secret-key: {{ $cuSecretKey }}
  cu-redirect-uri: {{ $cuRedirectUri }}
  cu-jwt-key: {{ $cuJwtKey }}
