  name: Despliegue continuo a QA
  on:
    push:
      branches:
        - 'hotfix/*'
        - 'release/*'
  jobs:
    setup-build:
      name: Configurar, Construir
      runs-on: ubuntu-latest
      env:
        PROJECT_ID: ${{ secrets.CGP_PROJECT }}
        KEY: ${{ secrets.GCP_KEY }}
        API_ZONE: ${{ secrets.GCP_ZONE_QA }}
        API_CLUSTER: ${{ secrets.GCP_CLUSTER_QA }}
        API_KEY: ${{ secrets.API_KEY_QA }}
        MONGO_IP: ${{ secrets.MONGO_IP_QA }}
        JWT_REFRESH_KEY: ${{ secrets.JWT_REFRESH_KEY }}
        CU_CLIENT_KEY: ${{ secrets.CU_CLIENT_KEY_QA }}
        CU_SECRET_KEY: ${{ secrets.CU_SECRET_KEY_QA }}
        CU_REDIRECT_URI: ${{ secrets.CU_REDIRECT_URI_QA }}
        CU_JWT_KEY: ${{ secrets.CU_JWT_KEY }}
        NODE_ENV: "dev"
        I_JWT_KEY: ${{ secrets.I_JWT_KEY_QA }}
        I_JWT_KEY_REFRESH: ${{ secrets.I_JWT_KEY_REFRESH_QA }}
        API_URL: ${{ secrets.API_URL_QA }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Build Test
          env:
            #Variables usadas solo para la ejecución de las pruebas
            MONGO_URI: "mongodb://localhost:27017/hrapp_dev"
            PORT: "3000"
            HOST_NAME: "localhost"
            JWT_SECRET: "TEST"
            JWT_SECRET_REFRESH_TOKEN: "TEST"
            CLIENT_ID: "TEST"
            CLIENT_SECRET: "TEST"
            REDIRECT_URI: "http://redirect-uri/v1/clave-unica"
            JWT_SECRET_CLAVE_UNICA: "TEST"
            JWT_SECRET_INTERNO: "TEST"
            JWT_SECRET_REFRESH_TOKEN_INTERNO: "TEST"
            API_URL: "http://localhost:3000"
          run: |
            chmod +x ./gradlew
            ./gradlew helmInstallToCloud